# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/lime/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lime,lemon,pomelo,chime,juice)

endif
